// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

type Group struct {
	GroupID   int32
	Groupname string
}

type GroupRole struct {
	GroupID int32
	RoleID  int32
}

type Role struct {
	RoleID   int32
	Rolename string
}

type User struct {
	UserID   int32
	Name     string
	Password string
}

type UserGroup struct {
	UserID  int32
	GroupID int32
}

type UserRole struct {
	UserID int32
	RoleID int32
}
